C_NETWORK_CONNECT=1
C_CREATE_USER=2
C_NETWORK_CHOOSE_CHAR=3
C_USER_ADD_CHAR=9
C_USER_DELETE_CHAR=10

C_CONNEXION_OK=0
C_CONNEXION_NOACCOUNT=1
C_CONNEXION_WRONGPWD=2
C_CONNEXION_ALREADYCONNECTED=3

C_NETWORK_INFO_ZONE=4
C_NETWORK_USER_CHOOSE_HERO=6
#~ C_NETWORK_CHANGE_ZONE=7
C_NETWORK_INFO_ZONE=8
C_NETWORK_USER_CHANGE_ZONE=11
C_NETWORK_DEATH_CHAR=12
C_NETWORK_DEATH_CHAR_STEP2=13
C_NETWORK_APPEND_READ_DIALOG=14
C_NETWORK_ASK_READ_DIALOG=15
C_NETWORK_CHARACTER_UNINSTALL_SLOT=16
C_NETWORK_CHARACTER_INSTALL_SLOT=17
C_NETWORK_CHARACTER_ADD_TO_INVENTORY=18
C_NETWORK_CHARACTER_ACCEPT_MISSION=19
C_NETWORK_CHARACTER_CANCEL_MISSION=20
C_NETWORK_CHARACTER_BUY_ITEM=22
C_NETWORK_CHARACTER_SELL_ITEM=23
C_NETWORK_CHARACTER_INV2STATION=24
C_NETWORK_CHARACTER_STATION2INV=25

