C_NETWORK_CONNECT=1
C_CREATE_USER=2
C_NETWORK_CHOOSE_CHAR=3
C_USER_ADD_CHAR=9
C_USER_DELETE_CHAR=10

C_CONNEXION_OK=0
C_CONNEXION_NOACCOUNT=1
C_CONNEXION_WRONGPWD=2
C_CONNEXION_ALREADYCONNECTED=3

C_NETWORK_INFO_ZONE=4
C_NETWORK_USER_CHOOSE_HERO=6
C_NETWORK_INFO_ZONE=8
C_NETWORK_USER_CHANGE_ZONE=11
C_NETWORK_DEATH_CHAR=12
C_NETWORK_DEATH_CHAR_STEP2=13
C_NETWORK_APPEND_READ_DIALOG=14
C_NETWORK_ASK_READ_DIALOG=15