##########ITEM TYPE###############
C_ITEM_ENGINE=1
C_ITEM_WEAPON=2
C_ITEM_ENERGY=3
C_ITEM_CONTAINER=4
C_ITEM_ELECTRO=5
C_ITEM_RADAR=6
C_ITEM_SHIP=7
C_ITEM_MINING=10
C_ITEM_MINERAL=11
C_ITEM_SHIELD=12
##########SLOT LOCATION###############
C_SLOT_FRONT=1
C_SLOT_REAR=2
C_SLOT_LEFT=3
C_SLOT_RIGHT=4
C_SLOT_MIDDLE=5