C_NETWORK_CONNECT=1
C_CREATE_USER=2
C_USER_ADD_CHAR=9
C_USER_DELETE_CHAR=10

C_CONNEXION_OK=0
C_CONNEXION_NOACCOUNT=1
C_CONNEXION_WRONGPWD=2
C_CONNEXION_ALREADYCONNECTED=3

C_NETWORK_INFO_ZONE=4
C_NETWORK_USER_CHOOSE_HERO=6
C_NETWORK_INFO_ZONE=8