C_BEHAVIOR_PATROL=1
C_BEHAVIOR_ATTACK=2
C_BEHAVIOR_DODGE=3


C_BEHAVIOR_STATUS_CURRENT=1
C_BEHAVIOR_STATUS_FINISHED=2

C_FACTOR_TORQUE=30
C_VELOCITY=50.0

C_ATTITUDE_AGGRESSIVITE=1
C_ATTITUDE_DEFENSE=2
C_LOYAUTE=3